### ISSUE TITLE
IDS

### ISSUE THREAD

**Issue by GhostFire90** [techbelly/di-usb-library#4]
Got all of the code working, emailed you already but i fear no response so here i am, How did you get the IDS for the "Color.py" example? I would really like to know, thank you

**Comment by techbelly** [comment]
Hi there, it's a while ago now, but I think I just put some of the figures I had on the base and printed out the ids returned by the library. I don't think that they'll work across figures - so your spiderman might have a different id to mine. Hope that helps.

**Comment by GhostFire90** [comment]
What command in the lib would I use for that? If you remember

**Comment by GhostFire90** [comment]
How would i get it to return the ids? GetAllTags requires me to have it do something but idk what i should do

**Comment by GhostFire90** [comment]
NEVERMIND, for people who find this, here is how you do it
def printTags(base_to_tag):
    for b in [1, 2, 3]:
        if b in base_to_tag:
            people = base_to_tag[b]
            print(people)
def updatePrint():
    base.getAllTags(printTags)
base.onTagsChanged = updatePrint
updatePrint()
